### ISSUE TITLE
Should SSD1306 compatibles be added?

### ISSUE THREAD

**Issue by shuyuan-liu** [adafruit/I2C_Addresses#6]
This could include for example:
- Sino Wealth SH1106: Very common, same addresses. Mostly compatible but without "memory addressing modes".
- Chip Wealth CH1116: Newer chip from the same company under a different name. Seems to be getting more common mostly in China. Same addresses. No "memory addressing modes".
- SSD1309
- SSD1315

**Comment by ladyada** [comment]
yep please submit a PR for any chips you find1
